text = "Bilal Shahid from Swabi"
print(text)
upper_text = text.upper()
print(upper_text)
lower_text = text.lower()
print(lower_text)
title_text = text.title()
print(title_text)
capitalized_text = text.capitalize()
print(capitalized_text)
swapped_text = text.swapcase()
print(swapped_text) 
stripped_text = text.strip()
print(stripped_text)
replaced_text = text.replace("Swabi", "Mardan")
print(replaced_text)
find_text = text.find("Swabi")
print(find_text)
counted_text = text.count("a")
print(counted_text)
startwith_text = text.startswith("Bilal")
print(startwith_text)
endwith_text = text.endswith("Swabi")
print(endwith_text)
split_text = text.split(" ")
print(split_text)
joined_text = "-".join(split_text)
print(joined_text)
isalpha_text = text.isalpha()
print(isalpha_text)
isdigit_text = text.isdigit()
print(isdigit_text)
